version: '3'

services:
  node:
    container_name: scoreshelf_server
    image: scoreshelf_server:latest
    entrypoint: ['npm', 'run', 'dev']
    tty: true
    ports:
      - 3000:3000
      - 9229:9229
    working_dir: '/var/server/'
    volumes:
      - ./:/var/server
